### PR TITLE
add performace audit

### PR DESCRIPTION
**Pull request by richardoppiyo**
In this milestone, my coding partner @Thi-Ponce and @richardoppiyo  worked on adding performance audit to the database.

### CODE REVIEW

**Comment by richardoppiyo** [comment]
The results for the first query: SELECT COUNT(*) FROM visits where animal_id = 4

1.Befor:
Screenshot 2022-05-02 at 23 30 42

2.After:
Screenshot 2022-05-02 at 23 59 14

**Comment by richardoppiyo** [comment]
The result for the 2nd query: SELECT * FROM visits where vet_id = 2;

1.Before:
Screenshot 2022-05-02 at 23 31 08

2. After:

Screenshot 2022-05-03 at 01 14 12

**Comment by richardoppiyo** [comment]
The third query: SELECT * FROM owners where email = 'owner_18327@mail.com';

1.Before
Screenshot 2022-05-02 at 23 31 28


2.After:
Screenshot 2022-05-03 at 00 35 23

**Review by andersonlebon — APPROVED** [review]
## Hi @richardoppiyo 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

nodding-yes
## Optional suggestions
- [ ] Kindly Check the comments under the review._
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Pull request merged**
